#ifndef ZETASQL_PUBLIC_SIMPLE_TABLE_CC_PROTO_EXPORT_H
#define ZETASQL_PUBLIC_SIMPLE_TABLE_CC_PROTO_EXPORT_H

#include "zetasql/public/simple_table.pb.h"
#include "zetasql/public/simple_table.pb.cc"

#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/annotation_cc_proto/export.inc"
#include "go-zetasql/public/simple_value_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
