#ifndef ZETASQL_SCRIPTING_SCRIPT_EXECUTOR_STATE_CC_PROTO_EXPORT_H
#define ZETASQL_SCRIPTING_SCRIPT_EXECUTOR_STATE_CC_PROTO_EXPORT_H

#include "zetasql/scripting/script_executor_state.pb.h"
#include "zetasql/scripting/script_executor_state.pb.cc"

#include "go-zetasql/proto/function_cc_proto/export.inc"
#include "go-zetasql/scripting/variable_cc_proto/export.inc"
#include "go-zetasql/scripting/script_exception_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
