#ifndef ZETASQL_PARSER_PARSE_TREE_CC_PROTO_EXPORT_H
#define ZETASQL_PARSER_PARSE_TREE_CC_PROTO_EXPORT_H

#include "zetasql/parser/parse_tree.pb.h"
#include "zetasql/parser/parse_tree.pb.cc"

#include "go-zetasql/parser/ast_enums_cc_proto/export.inc"
#include "go-zetasql/public/parse_location_range_cc_proto/export.inc"
#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
