#ifndef ZETASQL_BASE_ARENA_ALLOCATOR_EXPORT_H
#define ZETASQL_BASE_ARENA_ALLOCATOR_EXPORT_H

#include "zetasql/base/arena_allocator.h"

#include "zetasql/base/arena_allocator.cc"

#if 0
namespace zetasql_base {

  void Gladiator::UnusedKeyMethod() {}

}
#endif

#include "go-zetasql/base/arena/export.inc"
#include "go-zetasql/base/logging/export.inc"
#include "go-absl/base/core_headers/export.inc"

#endif
