
extern void GO_EXPORT(TypeFactory_MakeArrayType)(void * arg0,void * arg1,void ** arg2,void ** arg3);
extern void GO_EXPORT(TypeFactory_MakeStructType)(void * arg0,void * arg1,void ** arg2,void ** arg3);
extern void GO_EXPORT(Int32Type)(void ** arg0);
extern void GO_EXPORT(Int64Type)(void ** arg0);
extern void GO_EXPORT(Uint32Type)(void ** arg0);
extern void GO_EXPORT(Uint64Type)(void ** arg0);
extern void GO_EXPORT(BoolType)(void ** arg0);
extern void GO_EXPORT(FloatType)(void ** arg0);
extern void GO_EXPORT(DoubleType)(void ** arg0);
extern void GO_EXPORT(StringType)(void ** arg0);
extern void GO_EXPORT(BytesType)(void ** arg0);
extern void GO_EXPORT(DateType)(void ** arg0);
extern void GO_EXPORT(TimestampType)(void ** arg0);
extern void GO_EXPORT(TimeType)(void ** arg0);
extern void GO_EXPORT(DatetimeType)(void ** arg0);
extern void GO_EXPORT(IntervalType)(void ** arg0);
extern void GO_EXPORT(GeographyType)(void ** arg0);
extern void GO_EXPORT(NumericType)(void ** arg0);
extern void GO_EXPORT(BigNumericType)(void ** arg0);
extern void GO_EXPORT(JsonType)(void ** arg0);
extern void GO_EXPORT(EmptyStructType)(void ** arg0);
extern void GO_EXPORT(Int32ArrayType)(void ** arg0);
extern void GO_EXPORT(Int64ArrayType)(void ** arg0);
extern void GO_EXPORT(Uint32ArrayType)(void ** arg0);
extern void GO_EXPORT(Uint64ArrayType)(void ** arg0);
extern void GO_EXPORT(BoolArrayType)(void ** arg0);
extern void GO_EXPORT(FloatArrayType)(void ** arg0);
extern void GO_EXPORT(DoubleArrayType)(void ** arg0);
extern void GO_EXPORT(StringArrayType)(void ** arg0);
extern void GO_EXPORT(BytesArrayType)(void ** arg0);
extern void GO_EXPORT(TimestampArrayType)(void ** arg0);
extern void GO_EXPORT(DateArrayType)(void ** arg0);
extern void GO_EXPORT(DatetimeArrayType)(void ** arg0);
extern void GO_EXPORT(TimeArrayType)(void ** arg0);
extern void GO_EXPORT(IntervalArrayType)(void ** arg0);
extern void GO_EXPORT(GeographyArrayType)(void ** arg0);
extern void GO_EXPORT(NumericArrayType)(void ** arg0);
extern void GO_EXPORT(BigNumericArrayType)(void ** arg0);
extern void GO_EXPORT(JsonArrayType)(void ** arg0);
extern void GO_EXPORT(DatePartEnumType)(void ** arg0);
extern void GO_EXPORT(NormalizeModeEnumType)(void ** arg0);
extern void GO_EXPORT(SimpleColumn_new)(void * arg0,void * arg1,void * arg2,void ** arg3);
extern void GO_EXPORT(SimpleColumn_new_with_opt)(void * arg0,void * arg1,void * arg2,int arg3,int arg4,void ** arg5);
extern void GO_EXPORT(SimpleTable_new)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(Table_Name)(void * arg0,void ** arg1);
extern void GO_EXPORT(Table_FullName)(void * arg0,void ** arg1);
extern void GO_EXPORT(Table_NumColumns)(void * arg0,int* arg1);
extern void GO_EXPORT(Table_Column)(void * arg0,int arg1,void ** arg2);
extern void GO_EXPORT(Table_PrimaryKey_num)(void * arg0,int* arg1);
extern void GO_EXPORT(Table_PrimaryKey)(void * arg0,int arg1,int* arg2);
