#ifndef ZETASQL_PUBLIC_PROTO_TYPE_ANNOTATION_CC_PROTO_EXPORT_H
#define ZETASQL_PUBLIC_PROTO_TYPE_ANNOTATION_CC_PROTO_EXPORT_H

#include "zetasql/public/proto/type_annotation.pb.h"
#include "zetasql/public/proto/type_annotation.pb.cc"

#include "zetasql/public/proto/wire_format_annotation.pb.h"
#include "zetasql/public/proto/wire_format_annotation.pb.cc"

#include "go-protobuf/protobuf/export.inc"

#endif
