#ifndef ZETASQL_SCRIPTING_VARIABLE_CC_PROTO_EXPORT_H
#define ZETASQL_SCRIPTING_VARIABLE_CC_PROTO_EXPORT_H

#include "zetasql/scripting/variable.pb.h"
#include "zetasql/scripting/variable.pb.cc"

#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value_cc_proto/export.inc"
#include "go-zetasql/public/type_parameters_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
