
extern void GO_EXPORT(cctz_FixedOffsetFromName)(void * arg0,void * arg1,char* arg2);
extern void GO_EXPORT(cctz_FixedOffsetToName)(void * arg0,void ** arg1);
extern void GO_EXPORT(cctz_FixedOffsetToAbbr)(void * arg0,void ** arg1);
extern void GO_EXPORT(cctz_detail_format)(void * arg0,void * arg1,void * arg2,void * arg3,void ** arg4);
extern void GO_EXPORT(cctz_detail_parse)(void * arg0,void * arg1,void * arg2,void * arg3,void * arg4,void * arg5,char* arg6);
extern void GO_EXPORT(TimeZoneIf_Load)(void * arg0,void ** arg1);
extern void GO_EXPORT(time_zone_Impl_UTC)(void ** arg0);
extern void GO_EXPORT(time_zone_Impl_LoadTimeZone)(void * arg0,void * arg1,char* arg2);
extern void GO_EXPORT(time_zone_Impl_ClearTimeZoneMapTestOnly)();
extern void GO_EXPORT(time_zone_Impl_UTCImpl)(void ** arg0);
extern void GO_EXPORT(TimeZoneInfo_Load)(void * arg0,void * arg1,char* arg2);
extern void GO_EXPORT(TimeZoneInfo_BreakTime)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(TimeZoneInfo_MakeTime)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(TimeZoneInfo_Version)(void * arg0,void ** arg1);
extern void GO_EXPORT(TimeZoneInfo_Description)(void * arg0,void ** arg1);
extern void GO_EXPORT(TimeZoneInfo_NextTransition)(void * arg0,void * arg1,void * arg2,char* arg3);
extern void GO_EXPORT(TimeZoneInfo_PrevTransition)(void * arg0,void * arg1,void * arg2,char* arg3);
extern void GO_EXPORT(TimeZoneLibC_BreakTime)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(TimeZoneLibC_MakeTime)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(TimeZoneLibC_Version)(void * arg0,void ** arg1);
extern void GO_EXPORT(TimeZoneLibC_NextTransition)(void * arg0,void * arg1,void * arg2,char* arg3);
extern void GO_EXPORT(TimeZoneLibC_PrevTransition)(void * arg0,void * arg1,void * arg2,char* arg3);
extern void GO_EXPORT(time_zone_name)(void ** arg0);
extern void GO_EXPORT(time_zone_lookup)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(time_zone_lookup2)(void * arg0,void * arg1,void ** arg2);
extern void GO_EXPORT(time_zone_next_transition)(void * arg0,void * arg1,char* arg2);
extern void GO_EXPORT(time_zone_prev_transition)(void * arg0,void * arg1,char* arg2);
extern void GO_EXPORT(time_zone_version)(void * arg0,void ** arg1);
extern void GO_EXPORT(time_zone_description)(void * arg0,void ** arg1);
extern void GO_EXPORT(cctz_load_time_zone)(void * arg0,void * arg1,char* arg2);
extern void GO_EXPORT(cctz_utc_time_zone)(void ** arg0);
extern void GO_EXPORT(cctz_fixed_time_zone)(void * arg0,void ** arg1);
extern void GO_EXPORT(cctz_local_time_zone)(void ** arg0);
extern void GO_EXPORT(cctz_ParsePosixSpec)(void * arg0,void * arg1,char* arg2);
