// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zetasql/proto/internal_error_location.proto

#ifndef PROTOBUF_INCLUDED_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
#define PROTOBUF_INCLUDED_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "zetasql/public/error_location.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto 

namespace protobuf_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
namespace zetasql {
class InternalErrorLocation;
class InternalErrorLocationDefaultTypeInternal;
extern InternalErrorLocationDefaultTypeInternal _InternalErrorLocation_default_instance_;
}  // namespace zetasql
namespace google {
namespace protobuf {
template<> ::zetasql::InternalErrorLocation* Arena::CreateMaybeMessage<::zetasql::InternalErrorLocation>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace zetasql {

// ===================================================================

class InternalErrorLocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zetasql.InternalErrorLocation) */ {
 public:
  InternalErrorLocation();
  virtual ~InternalErrorLocation();

  InternalErrorLocation(const InternalErrorLocation& from);

  inline InternalErrorLocation& operator=(const InternalErrorLocation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InternalErrorLocation(InternalErrorLocation&& from) noexcept
    : InternalErrorLocation() {
    *this = ::std::move(from);
  }

  inline InternalErrorLocation& operator=(InternalErrorLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const InternalErrorLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InternalErrorLocation* internal_default_instance() {
    return reinterpret_cast<const InternalErrorLocation*>(
               &_InternalErrorLocation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(InternalErrorLocation* other);
  friend void swap(InternalErrorLocation& a, InternalErrorLocation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InternalErrorLocation* New() const final {
    return CreateMaybeMessage<InternalErrorLocation>(NULL);
  }

  InternalErrorLocation* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InternalErrorLocation>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InternalErrorLocation& from);
  void MergeFrom(const InternalErrorLocation& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InternalErrorLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .zetasql.ErrorSource error_source = 5;
  int error_source_size() const;
  void clear_error_source();
  static const int kErrorSourceFieldNumber = 5;
  ::zetasql::ErrorSource* mutable_error_source(int index);
  ::google::protobuf::RepeatedPtrField< ::zetasql::ErrorSource >*
      mutable_error_source();
  const ::zetasql::ErrorSource& error_source(int index) const;
  ::zetasql::ErrorSource* add_error_source();
  const ::google::protobuf::RepeatedPtrField< ::zetasql::ErrorSource >&
      error_source() const;

  // optional string filename = 4;
  bool has_filename() const;
  void clear_filename();
  static const int kFilenameFieldNumber = 4;
  const ::std::string& filename() const;
  void set_filename(const ::std::string& value);
  #if LANG_CXX11
  void set_filename(::std::string&& value);
  #endif
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  ::std::string* mutable_filename();
  ::std::string* release_filename();
  void set_allocated_filename(::std::string* filename);

  // optional int32 byte_offset = 3;
  bool has_byte_offset() const;
  void clear_byte_offset();
  static const int kByteOffsetFieldNumber = 3;
  ::google::protobuf::int32 byte_offset() const;
  void set_byte_offset(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zetasql.InternalErrorLocation)
 private:
  void set_has_byte_offset();
  void clear_has_byte_offset();
  void set_has_filename();
  void clear_has_filename();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::zetasql::ErrorSource > error_source_;
  ::google::protobuf::internal::ArenaStringPtr filename_;
  ::google::protobuf::int32 byte_offset_;
  friend struct ::protobuf_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InternalErrorLocation

// optional int32 byte_offset = 3;
inline bool InternalErrorLocation::has_byte_offset() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void InternalErrorLocation::set_has_byte_offset() {
  _has_bits_[0] |= 0x00000002u;
}
inline void InternalErrorLocation::clear_has_byte_offset() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void InternalErrorLocation::clear_byte_offset() {
  byte_offset_ = 0;
  clear_has_byte_offset();
}
inline ::google::protobuf::int32 InternalErrorLocation::byte_offset() const {
  // @@protoc_insertion_point(field_get:zetasql.InternalErrorLocation.byte_offset)
  return byte_offset_;
}
inline void InternalErrorLocation::set_byte_offset(::google::protobuf::int32 value) {
  set_has_byte_offset();
  byte_offset_ = value;
  // @@protoc_insertion_point(field_set:zetasql.InternalErrorLocation.byte_offset)
}

// optional string filename = 4;
inline bool InternalErrorLocation::has_filename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void InternalErrorLocation::set_has_filename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void InternalErrorLocation::clear_has_filename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void InternalErrorLocation::clear_filename() {
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_filename();
}
inline const ::std::string& InternalErrorLocation::filename() const {
  // @@protoc_insertion_point(field_get:zetasql.InternalErrorLocation.filename)
  return filename_.GetNoArena();
}
inline void InternalErrorLocation::set_filename(const ::std::string& value) {
  set_has_filename();
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zetasql.InternalErrorLocation.filename)
}
#if LANG_CXX11
inline void InternalErrorLocation::set_filename(::std::string&& value) {
  set_has_filename();
  filename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zetasql.InternalErrorLocation.filename)
}
#endif
inline void InternalErrorLocation::set_filename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_filename();
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zetasql.InternalErrorLocation.filename)
}
inline void InternalErrorLocation::set_filename(const char* value, size_t size) {
  set_has_filename();
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zetasql.InternalErrorLocation.filename)
}
inline ::std::string* InternalErrorLocation::mutable_filename() {
  set_has_filename();
  // @@protoc_insertion_point(field_mutable:zetasql.InternalErrorLocation.filename)
  return filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InternalErrorLocation::release_filename() {
  // @@protoc_insertion_point(field_release:zetasql.InternalErrorLocation.filename)
  if (!has_filename()) {
    return NULL;
  }
  clear_has_filename();
  return filename_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InternalErrorLocation::set_allocated_filename(::std::string* filename) {
  if (filename != NULL) {
    set_has_filename();
  } else {
    clear_has_filename();
  }
  filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:zetasql.InternalErrorLocation.filename)
}

// repeated .zetasql.ErrorSource error_source = 5;
inline int InternalErrorLocation::error_source_size() const {
  return error_source_.size();
}
inline ::zetasql::ErrorSource* InternalErrorLocation::mutable_error_source(int index) {
  // @@protoc_insertion_point(field_mutable:zetasql.InternalErrorLocation.error_source)
  return error_source_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::zetasql::ErrorSource >*
InternalErrorLocation::mutable_error_source() {
  // @@protoc_insertion_point(field_mutable_list:zetasql.InternalErrorLocation.error_source)
  return &error_source_;
}
inline const ::zetasql::ErrorSource& InternalErrorLocation::error_source(int index) const {
  // @@protoc_insertion_point(field_get:zetasql.InternalErrorLocation.error_source)
  return error_source_.Get(index);
}
inline ::zetasql::ErrorSource* InternalErrorLocation::add_error_source() {
  // @@protoc_insertion_point(field_add:zetasql.InternalErrorLocation.error_source)
  return error_source_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::zetasql::ErrorSource >&
InternalErrorLocation::error_source() const {
  // @@protoc_insertion_point(field_list:zetasql.InternalErrorLocation.error_source)
  return error_source_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace zetasql

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_zetasql_2fproto_2finternal_5ferror_5flocation_2eproto
