#ifndef ZETASQL_RESOLVED_AST_SERIALIZATION_CC_PROTO_EXPORT_H
#define ZETASQL_RESOLVED_AST_SERIALIZATION_CC_PROTO_EXPORT_H

#include "zetasql/resolved_ast/serialization.pb.h"
#include "zetasql/resolved_ast/serialization.pb.cc"

#include "go-zetasql/public/type_cc_proto/export.inc"
#include "go-zetasql/public/value_cc_proto/export.inc"
#include "go-zetasql/public/annotation_cc_proto/export.inc"
#include "go-zetasql/public/parse_location_range_cc_proto/export.inc"
#include "go-protobuf/protobuf/export.inc"

#endif
